### ISSUE TITLE
Will cause the Events/Agenda java script fail when use this module 

### ISSUE THREAD

**Issue by trekmorris** [ATM-Consulting/dolibarr_module_fullcalendar#85]
If use this module on dolibarr , " Leave " calendar will not work when you click it .
And if you deactivate full calendar module , then you will see staff leave duration when you click " LEAVE " calendar .

Test Dolibarr version : 16.0.4 and 16.0.5

**Comment by Jozmichne** [comment]
I second that, this happened in my installation too.

**Comment by atm-lena** [comment]
Thank you for reporting it to us. 
Our team will work on it.

**Comment by Jozmichne** [comment]
@atm-lena , thank you, also not sure if it's related to the same issue but if there are other external calendars in the agenda confiigured they won't overlay on the module but if you turn it off you can see them.
